spring:
  profiles:
    active: local
    group:
      local: local, common, secret

---


spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:



server:
  port: 8080
  name: local

---

spring:
  config:
    activate:
      on-profile: common
  security:
    oauth2:
      client:
        registration:



